create database customer_behaviour;

select * from customer limit 20 ;


-- 1) what is the total revenue generated by male vs female customer ?

SELECT gender, sum(purchase_amount) as revenue 
from customer 
group by gender;




-- 2)  Which customers used a discount but still spent more than the average purchase amount ?
SELECT customer_id, purchase_amount
FROM `customer`
WHERE discount_applied = 'YES'
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM `customer`
  );


-- 3) which are the top 5 products with the highest average review rating ?

select item_purchased, round(AVG(review_rating) ,2) as "Average product rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- 4) Compare the avg purchase amount between standard and express shipping 
 
SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS avg_purchase
FROM `customer`
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- 5) Do subscribed customers spend more ? Compare average spend and total revenue between subscribers and non-subscribers

Select subscription_status,
count(customer_id) as total_customer,
Round(AVG(purchase_amount),2) as avg_spend,
round(SUM(purchase_amount),2) as total_revenue
from customer 
group by subscription_status
order by total_revenue, avg_spend desc;



-- 6) Which 5 products have the highest percentage of purchhase with discounts applied ?

SELECT item_purchased,
Round(SUM(CASE WHEN discount_applied = 'Yes' Then 1 Else 0 END) / count(*) * 100,2) as discount_rate 
from customer
group by item_purchased
order by discount_rate desc
limit 5 ;
 
 
 
-- 7) Segment customers into New, returning , and loyal based on their total 
-- number of previous purchase, and show the count of each segment. 

WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM `customer`
)

SELECT
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- 8) What are the top 3 most purchased products within each category ?

WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM `customer`
    GROUP BY category, item_purchased
)

SELECT
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;


-- 9) Are customers who are repeate buyers ( more than 5 perivious purchase) also likely to subscribe ?

Select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases > 5 
group by subscription_status;


-- 10) what is the revenue comtribution of each age group ?

Select age_groups,
sum(purchase_amount) as total_revenue
from customer
group by age_groups
order by total_revenue desc;
